# Archivo de constantes generado automáticamente

NODOS_ANILLO = 64
ROWS = 50
COLUMNS = 50
RED = 1
ROUTING = "RW-NODE2VEC"
P = 1
Q = 2
REGLA = 1
LONG_ENLACE = 2
CICLOS = 30
ENLACES_DINAMICOS = 2
EXPLORADORES = 20
DIV_CONEXIONES = 1
