# Archivo de constantes generado automáticamente

NODOS_ANILLO = 64
ROWS = 50
COLUMNS = 50
RED = 1
ROUTING = "RW-NODE2VEC"
P = 0.5
Q = 2
REGLA = 3
ALPHA = 0
VECTOR_POPULARIDAD = 0
VECTOR_DISTANCIA = 0
LONG_ENLACE = 2
CICLOS = 30
ENLACES_DINAMICOS = 2
EXPLORADORES = 20
DIV_CONEXIONES = 1
